version: '3'
services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=itapi
      - POSTGRES_PASSWORD=itapi_pass
      - POSTGRES_DB=itapi
    ports:
      - '5432:5432'

  issue-tracker-api:
    image: caju90/issue-tracker-api:latest
    container_name: issue-tracker-api
    environment:
      - POSTGRES_HOST=psql-db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=itapi
      - POSTGRES_USERNAME=itapi
      - POSTGRES_PASSWORD=itapi_pass
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
      - "8787:8787"
    depends_on:
      - psql-db
